# Generated by Django 4.2 on 2023-04-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReferEm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerefer',
            name='UploadResume',
        ),
        migrations.RemoveField(
            model_name='employeerefer',
            name='user',
        ),
    ]
